import Head from 'next/head';

export default function Home() {
  return (
    <div className="font-poppins">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Rahul Dhawan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Mali:ital@1&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,600&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet" />
      </Head>

      <div className="dark">
        <main className="bg-white px-10 dark:bg-zinc-900 md:px-20 lg:px-40">
          <section className="min-h-screen" id="banner">
            <nav className="bg-white pt-10 mb-12 flex justify-evenly sticky top-0 z-50 dark:bg-zinc-900 dark:text-white">
              <h1 className="font-burtons pl-5 text-xl"><a href="/">MatchStick</a></h1>
              <ul className="flex items-center">
                <li>
                  <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-4" href="#services">Services</a>
                  <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-4" href="#portfolio">Projects</a>
                </li>
                <li>
                  <a>
                    <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 16 16" className="cursor-pointer text-2xl ml-2" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path><path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path></svg>
                  </a>
                </li>
              </ul>
            </nav>

            <div className="text-center">
              <span className="text-3xl py-1 dark:text-white heads">Hello World, I'm</span>
              <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-8xl jumbo">Rahul Dhawan</h2>
              <div className="bg-white flex space-x-2 p-1 rounded-full justify-center items-center dark:bg-zinc-900">
                <div className="bg-blue-600 p-2 w-6 h-6 rounded-full animate-bounce blue-circle"></div>
                <div className="bg-green-600 p-2 w-4 h-4 rounded-full animate-bounce green-circle"></div>
                <div className="bg-red-600 p-2 w-6 h-6 rounded-full animate-bounce red-circle"></div>
              </div>
              <h3 className="text-2xl py-2 dark:text-gray-200 md:text-3xl marker">Developer and Designer.</h3>
            <h4 className="text-md desc py-5 leading-8 max-w-3xl text-gray-800 mx-auto md:text-xl dark:text-gray-200">
  Over the last couple of years, I acquired extensive experience as a Full-Stack Developer and built two start-ups. This journey empowered me to devise an end-to-end development process that brings out the best of my skills. Today, I am building scalable webapps powered by <span className="text-teal-500 dark:text-teal-400">GPT-4 and OpenAI</span>, architecting their infrastructure using <span className="text-teal-500 dark:text-teal-400">AWS (EC2, S3, CloudFront)</span> and securing them with ACM.
</h4>
<h4 className="text-md desc py-1 leading-8 text-gray-800 mx-auto md:text-xl dark:text-gray-200 max-w-3xl">
  By leveraging modern <span className="text-teal-500 dark:text-teal-400">DevOps practices</span>—including CI/CD pipelines, GitHub Actions, and seamless DNS integration—I ensure these applications are highly available and aimed at solving real-world challenges. Let's make something special!
</h4>
              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                <a href="https://github.com/RAhuLDHawaN-cmd">
                  <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M511.6 76.3C264.3 76.2 64 276.4 64 523.5 64 718.9 189.3 885 363.8 946c23.5 5.9 19.9-10.8 19.9-22.2v-77.5c-135.7 15.9-141.2-73.9-150.3-88.9C215 726 171.5 718 184.5 703c30.9-15.9 62.4 4 98.9 57.9 26.4 39.1 77.9 32.5 104 26 5.7-23.5 17.9-44.5 34.7-60.8-140.6-25.2-199.2-111-199.2-213 0-49.5 16.3-95 48.3-131.7-20.4-60.5 1.9-112.3 4.9-120 58.1-5.2 118.5 41.6 123.2 45.3 33-8.9 70.7-13.6 112.9-13.6 42.4 0 80.2 4.9 113.5 13.9 11.3-8.6 67.3-48.8 121.3-43.9 2.9 7.7 24.7 58.3 5.5 118 32.4 36.8 48.9 82.7 48.9 132.3 0 102.2-59 188.1-200 212.9a127.5 127.5 0 0 1 38.1 91v112.5c.8 9 0 17.9 15 17.9 177.1-59.7 304.6-227 304.6-424.1 0-247.2-200.4-447.3-447.5-447.3z"></path></svg>
                </a>
                <a href="https://www.linkedin.com/in/rahul-dhawan27/">
                  <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 1024 1024" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M880 112H144c-17.7 0-32 14.3-32 32v736c0 17.7 14.3 32 32 32h736c17.7 0 32-14.3 32-32V144c0-17.7-14.3-32-32-32zM349.3 793.7H230.6V411.9h118.7v381.8zm-59.3-434a68.8 68.8 0 1 1 68.8-68.8c-.1 38-30.9 68.8-68.8 68.8zm503.7 434H675.1V608c0-44.3-.8-101.2-61.7-101.2-61.7 0-71.2 48.2-71.2 98v188.9H423.7V411.9h113.8v52.2h1.6c15.8-30 54.5-61.7 112.3-61.7 120.2 0 142.3 79.1 142.3 181.9v209.4z"></path></svg>
                </a>
              </div>
              <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
                <img loading="lazy" className="object-cover w-full h-full" src="/dev-ed-wave.png" alt="Developer Wave" />
              </div>
            </div>
          </section>

          <section id="services">
            <div>
              <h3 className="text-3xl py-1 dark:text-white heads">Services offered</h3>

<p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl desc">
  Since the beginning of my journey as a freelance developer and designer, my expertise has evolved to include robust <span className="text-teal-500 dark:text-teal-400">Cloud Architecture</span> and <span className="text-teal-500 dark:text-teal-400">DevOps</span>. I've done remote work for agencies, consulted for startups, and collaborated with talented people to build, deploy, and scale digital products for both business and consumer use.
</p>
<p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl desc">
  I offer a comprehensive range of services, from programming and design to cloud hosting using <span className="text-teal-500 dark:text-teal-400">AWS (EC2, S3, CloudFront, ACM)</span>. My technical workflow also includes automating deployments with <span className="text-teal-500 dark:text-teal-400">CI/CD pipelines</span> and <span className="text-teal-500 dark:text-teal-400">GitHub Actions</span>, alongside handling complete DNS and Origin integrations.
</p>
            </div>
            <div className="lg:flex gap-10">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-700 flex-1">
                <img loading="lazy" className="animate-bounce mx-auto w-24 h-24" src="/design.png" alt="Design" />
                <h3 className="text-2xl font-medium pt-8 pb-2 dark:text-gray-200 service">Swift Designs</h3>
                <p className="py-2 dark:text-gray-200 Roboto">Creating elegant designs suited for design theory.</p>
                <h4 className="py-4 text-teal-600 dark:text-teal-400 text-xl">Tools I Use</h4>
                <p className="text-gray-800 py-1 dark:text-gray-200">Photoshop</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">XD</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Figma</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Indesign</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-700 flex-1">
                <img loading="lazy" className="animate-bounce mx-auto w-24 h-24" src="/code.png" alt="Code" />
                <h3 className="text-2xl font-medium pt-8 pb-2 dark:text-gray-200 Roboto">Responsive</h3>
                <p className="py-2 dark:text-gray-200 Roboto">Have a great website? Let's make it work on any device size.</p>
                <h4 className="py-4 text-teal-600 dark:text-teal-400 text-xl">Utilities I Use</h4>
                <p className="text-gray-800 py-1 dark:text-gray-200">Chrome Dev Tools</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Sublime Text</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Visual Studio Code</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Firefox Dev Tools</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-700 flex-1">
                <img loading="lazy" className="animate-bounce mx-auto w-24 h-24" src="/consulting.png" alt="Consulting" />
                <h3 className="text-2xl font-medium pt-8 pb-2 dark:text-gray-200 Roboto">Intuitive</h3>
                <p className="py-2 dark:text-gray-200 Roboto">Strong preference for easy to use, intuitive UX/UI.</p>
                <h4 className="py-4 text-teal-600 dark:text-teal-400 text-xl">Tools I Use</h4>
                <p className="text-gray-800 py-1 dark:text-gray-200">FluidUI</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Wix</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Figma</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Indesign</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-700 flex-1">
                <img loading="lazy" className="animate-bounce mx-auto w-24 h-24" src="/database.png" alt="Database" />
                <h3 className="text-2xl font-medium pt-8 pb-2 dark:text-gray-200 Roboto">Dynamic</h3>
                <p className="py-2 dark:text-gray-200 Roboto">Websites Static?, I love making pages come to life</p>
                <h4 className="py-4 text-teal-600 dark:text-teal-400 text-xl">Technologies I Use</h4>
                <p className="text-gray-800 py-1 dark:text-gray-200">Node</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Mongodb</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">Express</p>
                <p className="text-gray-800 py-1 dark:text-gray-200">ECMAScript</p>
              </div>
            </div>
          </section>

          <section className="py-10" id="portfolio">
            <div>
              <h3 className="text-3xl py-1 dark:text-white heads">Portofolio</h3>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl desc">Since the beginning of my journey as a freelance designer and developer, I've done remote work for<span className="text-teal-500 dark:text-teal-400"> agencies </span>consulted for <span className="text-teal-500 dark:text-teal-400">startups </span>and collaborated with talanted people to create digital products for both business and consumer use.</p>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl desc">I offer from a wide range of services, including brand design, programming and teaching.</p>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <a href="https://fooddie-live.herokuapp.com/">
                  <img loading="lazy" className="rounded-lg object-cover zoom w-full h-full" src="/web1.png" />
                </a>
              </div>
              <div className="basis-1/3 flex-1">
                <a href="https://fooddie-live.herokuapp.com/">
                  <img loading="lazy" className="rounded-lg object-cover zoom w-full h-full" src="/web2.png" />
                </a>
              </div>
              <div className="basis-1/3 flex-1">
                <a href="https://gptsynthesis.netlify.app/" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">
                  <img loading="lazy" className="rounded-lg object-cover zoom w-full h-full" src="/web7.png" />
                </a>
              </div>
              <div className="basis-1/3 flex-1">
                <a href="https://gptsynthesis.netlify.app/" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">
                  <img loading="lazy" className="rounded-lg object-cover zoom w-full h-full" src="/web8.png" />
                </a>
              </div>
              <div className="basis-1/3 flex-1">
                <a href="https://chat-worldd.netlify.app">
                  <img loading="lazy" className="rounded-lg object-cover zoom w-full h-full" src="/web3.png" />
                </a>
              </div>
              <div className="basis-1/3 flex-1">
                <a href="https://chat-worldd.netlify.app">
                  <img loading="lazy" className="rounded-lg object-cover zoom w-full h-full" src="/web4.png" />
                </a>
              </div>
              <div className="basis-1/3 flex-1">
                <a href="https://chat-worldd.netlify.app" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">
                  <img loading="lazy" className="rounded-lg object-cover zoom w-full h-full" src="/web5.png" />
                </a>
              </div>
              <div className="basis-1/3 flex-1">
                <a href="https://gptsysnthesis.netlify.app/" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">
                  <img loading="lazy" className="rounded-lg object-cover zoom w-full h-full" src="/web6.png" />
                </a>
              </div>
            </div>
          </section>

        </main>
      </div>
    </div>
  );
}